version: "3"

services:
  app:
    image: glopezep/users
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=production
      - DB_USERNAME=production
      - DB_PASSWORD=production

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=production
      - POSTGRES_USER=production
      - POSTGRES_PASSWROD=production
    volumes:
      - ./postgres-data:/var/lib/postgresql/data